pipeline:
  build:
    image: node:6.6.0
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: 120.25.92.210:5000/wodog/test
    tags: 1.1.0
    registry: 120.25.92.210:5000
    insecure: true
